### ISSUE TITLE
TLS certificate for noml.info is expired

### ISSUE THREAD

**Issue by girlbossceo** [Mojeek/noml-open-letter#101]
As the title says. I noticed it was expired for a couple days and figured it'd get noticed and resolved soon, but it doesn't appear to have been resolved yet.

<img width="900" alt="image" src="https://github.com/Mojeek/noml-open-letter/assets/112147643/feb9ccd1-059b-4379-b953-a3eab2ad5aaa">

**Comment by PrivacyDingus** [comment]
This [should be all good now](https://www.ssllabs.com/ssltest/analyze.html?d=noml.info) (apologies for the delay in reply), can I check you're not seeing this any more so I can close the issue? 🙏🏻

**Comment by girlbossceo** [comment]
Yes the website works now without any TLS errors.
