### ISSUE TITLE
SIGN: mirabilos

### ISSUE THREAD

**Issue by mirabilos** [Mojeek/noml-open-letter#13]
"name": "mirabilos",
"url": "http://www.mirbsd.org/",
"affiliation": "INDIVIDUAL",

**Comment by mirabilos** [comment]
Notes:

> and for non-HTML using:
>
> `X-Robots-Tag: noml`

This should be valid for both HTML and nōn-HTML; the user should not be forced to add this to all their HTML pages when they can deliver it via the HTTP header.

Also, `X-Robots-Tag: noai` has prior art, is in current use by many already, and AFAIHH at least one crawler for so-called “AI” (ML/LLM) recognises it. I’d therefore ask to standardise on _that_ instead.

**Comment by PrivacyDingus** [comment]
thanks for signing and the ```noai``` flag, will look into that; something like this is much needed
