### ISSUE TITLE
Wrong value in X-Robots-Tag header?

### ISSUE THREAD

**Issue by JacksonChen666** [Mojeek/noml-open-letter#30]
In the page, the following is presented:

```
<meta name="robots" content="noindex, nofollow, noml">
X-Robots-Tag: noindex, nofollow, noindex
```

The `noindex` thing appears twice in the `X-Robots-Tag` header, and it is marked as "not allowed for use in machine learning."

Maybe it was supposed to be like this?
```
X-Robots-Tag: noindex, nofollow, noml
```

**Comment by PrivacyDingus** [comment]
Thanks and good spot @JacksonChen666 🙏🏻
